# This file controls the AWS CodeBuild

version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
  build:
    commands:
    - echo "Entered build phase"
  #  - mvn clean prepare-package war:exploded
    - mvn clean package
  post_build:
    commands:
    - echo "Entered the post-build phase"
artifacts:
  files:
    - target/aws-elasticbeanstalk-cicd-0.0.1-SNAPSHOT.war
    - appspec.yml
